# -*- coding: utf-8 -*-
"""Quast_CRC_MAG_new.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11B0Tb8sQCsJSJJy3JjX1hxpP1PyhNb9n
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
import matplotlib.ticker as mticker
import os

# =======================================================
# Basic seaborn style (NO GRIDLINES)
# =======================================================
sns.set_style("white")

# =======================================================
# Functions for consistent black borders (Nature style)
# =======================================================
def style_axes(ax):
    """Apply thick black borders & remove gridlines."""
    ax.grid(False)
    for s in ax.spines.values():
        s.set_edgecolor("black")
        s.set_linewidth(2.0)


# =======================================================
# Load and process QUAST data
# =======================================================
simplified_file_path = "all_simplified_quast_combined.csv"
filtered_file_path   = "all_filtered_quast_combined.csv"

def load_and_process_quast(file_path, filter_status):
    if not os.path.exists(file_path):
        print(f"Error: File not found: {file_path}")
        return pd.DataFrame()

    df = pd.read_csv(file_path, sep=',')
    df.columns = df.columns.str.strip()

    if "Group" not in df.columns:
        print(f"Error: 'Group' column missing in {file_path}")
        return pd.DataFrame()

    df["Category"] = df["Group"]
    df["Filter_Status"] = filter_status
    return df

df_simplified = load_and_process_quast(simplified_file_path, "Simplified")
df_filtered   = load_and_process_quast(filtered_file_path, "Filtered")

df = pd.concat([df_simplified, df_filtered], ignore_index=True)
if df.empty:
    print("No data loaded. Exiting.")
    raise SystemExit

# =======================================================
# Convert numerical columns
# =======================================================
numeric_cols = ['# contigs', 'Largest contig', 'Total length', 'GC (%)',
                'N50', 'N75', 'L50', 'L75', "# N's per 100 kbp"]

for col in numeric_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

df = df.dropna(subset=["# contigs", "N50"])


# =======================================================
# Categories & color palette
# =======================================================
category_order = sorted(df["Category"].unique())
palette_map = dict(zip(category_order, sns.color_palette("tab10", n_colors=len(category_order)).as_hex()))

# =======================================================
# QUAST METRICS — BOX PLOTS (NO GRID, BLACK BORDERS)
# =======================================================
def plot_quast_metrics(subdf, status_label):
    metrics_to_plot = ["N50", "# contigs", "L50", "Total length"]
    fig, axes = plt.subplots(2, 2, figsize=(5, 5))
    axes = axes.flatten()

    for i, metric in enumerate(metrics_to_plot):
        ax = axes[i]
        sd = subdf[subdf[metric] > 0].copy()
        if sd.empty:
            ax.text(0.5, 0.5, f"No valid {metric}", ha="center", va="center")
            ax.axis("off")
            continue

        sns.boxplot(
            data=sd, x="Category", y=metric,
            palette=palette_map, order=category_order,
            ax=ax
        )

        ax.set_yscale("log")
        ax.set_xlabel("")
        ax.set_ylabel(metric)
        ax.set_xticklabels(category_order, rotation=45, ha="right", fontsize=7)

        style_axes(ax)

    plt.tight_layout()
    plt.savefig(f"Quast_boxplots_{status_label}.png", dpi=600, bbox_inches="tight")
    plt.close()
    print(f"[OK] Saved → Quast_boxplots_{status_label}.png")


# =======================================================
# SCATTER: N50 vs # contigs (NO GRID, BLACK BORDERS)
# =======================================================
def plot_n50_vs_contigs(subdf, status_label):
    sd = subdf[subdf["# contigs"] > 0].copy()
    if sd.empty:
        print(f"[skip] no contigs for {status_label}")
        return

    plt.figure(figsize=(4.2, 4))
    plt.xscale("log")

    ax = sns.scatterplot(
        data=sd,
        x="# contigs", y="N50",
        hue="Category", hue_order=category_order,
        palette=palette_map,
        s=35, alpha=0.7, edgecolor="black", linewidth=0.7
    )

    sns.regplot(
        data=sd, x="# contigs", y="N50",
        scatter=False, color="black", logx=True,
        line_kws={"linewidth": 2.0, "linestyle": "--"}
    )

    # R2
    clean = sd.dropna(subset=["# contigs", "N50"])
    r_value = stats.linregress(np.log10(clean["# contigs"]), clean["N50"]).rvalue
    ax.text(0.97, 0.92, f"R² = {r_value**2:.2f}",
            transform=ax.transAxes,
            fontsize=8, ha="right",
            bbox=dict(facecolor="white", alpha=0.4))

    ax.set_xlabel("Number of Contigs")
    ax.set_ylabel("N50")

    ax.legend(title="", fontsize=7, frameon=True, loc="center left",
              bbox_to_anchor=(1, 0.5))

    style_axes(ax)

    plt.tight_layout(rect=[0,0,0.82,1])
    plt.savefig(f"n50_vs_contigs_{status_label}.png", dpi=600, bbox_inches="tight")
    plt.close()
    print(f"[OK] Saved → n50_vs_contigs_{status_label}.png")


# =======================================================
# SCATTER: GC% vs N50 (NO GRID, BLACK BORDERS)
# =======================================================
def plot_gc_vs_n50_scatter(subdf, status_label):
    sd = subdf[subdf["N50"] > 0].copy()
    if sd.empty:
        print(f"[skip] no N50 for {status_label}")
        return

    plt.figure(figsize=(4, 4))
    sd = sd.dropna(subset=["GC (%)", "N50"])

    ax = sns.scatterplot(
        data=sd,
        x="GC (%)", y="N50",
        hue="Category", hue_order=category_order,
        palette=palette_map,
        s=32, alpha=0.7,
        edgecolor="black", linewidth=0.8
    )

    ax.set_yscale("log")
    ax.set_xlabel("GC Content (%)")
    ax.set_ylabel("N50")

    leg = ax.get_legend()
    if leg:
        leg.set_title("")
        leg.set_frame_on(True)
        plt.setp(leg.get_texts(), fontsize=6) # Fixed: changed leg.set_fontsize(6) to plt.setp(leg.get_texts(), fontsize=6)
        leg.set_bbox_to_anchor((1, 0.5))
        leg.set_loc("center left")

    style_axes(ax)

    plt.tight_layout(rect=[0,0,0.82,1])
    plt.savefig(f"gc_vs_n50_scatter_{status_label}.png", dpi=600, bbox_inches="tight")
    plt.close()
    print(f"[OK] Saved → gc_vs_n50_scatter_{status_label}.png")


# =======================================================
# Run plots for Filtered and Simplified
# =======================================================
df_filtered   = df[df["Filter_Status"] == "Filtered"]
df_simplified = df[df["Filter_Status"] == "Simplified"]

print("\n=== FILTERED DATA ===")
plot_quast_metrics(df_filtered, "Filtered")
plot_n50_vs_contigs(df_filtered, "Filtered")
plot_gc_vs_n50_scatter(df_filtered, "Filtered")

print("\n=== SIMPLIFIED DATA ===")
plot_quast_metrics(df_simplified, "Simplified")
plot_n50_vs_contigs(df_simplified, "Simplified")
plot_gc_vs_n50_scatter(df_simplified, "Simplified")
