# -*- coding: utf-8 -*-
"""Fastqscreen_CRC_Mags.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12OQj87Vq1vvr7KPpVzI4OZpJuIaY3k6E
"""

#############################################
# FastQ Screen contamination summary
# Corrected for Cohort_1 … Cohort_8 dataset
# Files: all_Fastqscreen_before1_combined.csv
#        all_Fastqscreen_before2_combined.csv
#############################################

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import re, os
from pathlib import Path

sns.set_style("white")

#############################################
# Files
#############################################
FILES = {
    "before1": "all_Fastqscreen_before1_combined.csv",
    "before2": "all_Fastqscreen_before2_combined.csv",
}

# Extract Cohorts dynamically
ORDER_GROUPS = [f"Cohort_{i}" for i in range(1, 9)]
COHORT_PALETTE = sns.color_palette("tab10", 8).as_hex()
PALETTE_GROUPS = dict(zip(ORDER_GROUPS, COHORT_PALETTE))

CONTAM_TARGETS = ["Human", "CHM13", "Mouse", "Vectors", "Plasmodium"]
PALETTE_CONTAM = dict(zip(CONTAM_TARGETS,
                          sns.color_palette("Set2", 5).as_hex()))


#############################################
# Helper functions
#############################################
def style_axes(ax):
    ax.grid(False)
    for s in ax.spines.values():
        s.set_edgecolor("black")
        s.set_linewidth(2.2)

def to_num(x):
    return pd.to_numeric(x.astype(str).str.replace("%","",regex=False)
                          .str.replace(",","",regex=False),
                         errors="coerce")

def compute_percent(unmapped, total):
    unm = to_num(unmapped)
    tot = to_num(total)
    return (unm / (tot + 1e-12)) * 100.0

#############################################
# Load and process both files
#############################################
parts = []

for rep, fpath in FILES.items():
    if not os.path.exists(fpath):
        raise FileNotFoundError(f"Missing file: {fpath}")

    df = pd.read_csv(fpath, dtype=str)
    df.columns = [c.strip() for c in df.columns]

    # Compute contamination percentages per contaminant
    pu_human   = compute_percent(df["unmapped_Human"], df["Reads_processed"])
    pu_chm13   = compute_percent(df["unmapped_CHM13"], df["Reads_processed"])
    pu_mouse   = compute_percent(df["unmapped_Mouse"], df["Reads_processed"])
    pu_vectors = compute_percent(df["unmapped_Vectors"], df["Reads_processed"])
    pu_plas    = compute_percent(df["unmapped_Plasmodium"], df["Reads_processed"])

    part = pd.DataFrame({
        "Sample_ID": df["Sample_ID"].str.strip(),
        "Group":     df["Group"].str.strip(),
        "Replicate": rep,

        # Convert "percent unmapped" → "percent mapped (contamination)"
        "Contam_Human":      100 - pu_human,
        "Contam_CHM13":      100 - pu_chm13,
        "Contam_Mouse":      100 - pu_mouse,
        "Contam_Vectors":    100 - pu_vectors,
        "Contam_Plasmodium": 100 - pu_plas,
    })

    parts.append(part)

df = pd.concat(parts, ignore_index=True)
df["Group"] = pd.Categorical(df["Group"], categories=ORDER_GROUPS, ordered=True)

#############################################
# Pivot to wide format R1/R2
#############################################
df["RepShort"] = df["Replicate"].map({"before1":"R1", "before2":"R2"})

wide = df.pivot_table(
    index=["Sample_ID","Group"],
    columns="RepShort",
    values=["Contam_Human","Contam_CHM13","Contam_Mouse",
            "Contam_Vectors","Contam_Plasmodium"],
    aggfunc="first",
    observed=True,
)

wide.columns = [f"{rep}_{lib}".replace("Contam_","")
                for lib, rep in wide.columns]
wide = wide.reset_index()

#############################################
# Compute averages across R1/R2
#############################################
avg_cols = []
for lib in ["Human","CHM13","Mouse","Vectors","Plasmodium"]:
    cols = [c for c in wide.columns if re.match(fr"R[12]_{lib}", c)]
    wide[f"Avg_{lib}"] = wide[cols].mean(axis=1, skipna=True)
    avg_cols.append(f"Avg_{lib}")

#############################################
# Save Table 1
#############################################
wide.to_csv("table1_contamination_per_sample_wide.tsv",
            sep="\t", index=False)

#############################################
# Table 2 Group Mean ± SD
#############################################
grp_stats = wide.groupby("Group")[avg_cols].agg(["mean","std"])
grp_stats.columns = [f"{lib} {stat}" for lib, stat in grp_stats.columns]
grp_stats = grp_stats.reset_index()
grp_stats.to_csv("table2_group_mean_sd.tsv", sep="\t", index=False)

#############################################
# Table 3 ANOVA
#############################################
anova_rows=[]
for lib in avg_cols:
    groups=[]
    for g in ORDER_GROUPS:
        v = wide.loc[wide["Group"]==g, lib].dropna()
        if len(v)>0: groups.append(v)
    if len(groups)>=2:
        F,p = stats.f_oneway(*groups)
        anova_rows.append({
            "Contaminant": lib.replace("Avg_",""),
            "F-statistic": round(F,4),
            "p-value": p,
            "Significant": "Yes" if p<0.05 else "No",
        })

pd.DataFrame(anova_rows).to_csv("table3_anova.tsv",sep="\t",index=False)

#############################################
# PLOT A — Total contamination
#############################################
wide["Total_Contam"] = wide[avg_cols].sum(axis=1)

tot = (wide.groupby("Group")["Total_Contam"]
       .mean().reindex(ORDER_GROUPS).reset_index())

plt.figure(figsize=(4,5))
ax = sns.barplot(
    data=tot, x="Group", y="Total_Contam",
    palette=PALETTE_GROUPS, edgecolor="black"
)
for i,r in tot.iterrows():
    ax.text(i, r["Total_Contam"]*1.02, f"{r['Total_Contam']:.1f}",
            ha="center", fontsize=9)
style_axes(ax)
plt.xticks(rotation=60, ha="right")
plt.ylabel("Mean total contamination (%)")
plt.tight_layout()
plt.savefig("plot_total_contamination_by_cohort.png",dpi=600)
plt.close()

#############################################
# PLOT B — Stacked contamination means
#############################################
stack = wide.groupby("Group")[avg_cols].mean().reindex(ORDER_GROUPS)
stack.columns = [c.replace("Avg_","") for c in stack.columns]

ax = stack.plot(
    kind="bar", stacked=True, figsize=(3,3),
    edgecolor="black",
    color=[PALETTE_CONTAM[k] for k in CONTAM_TARGETS]
)
style_axes(ax)
plt.xticks(rotation=60, ha="right")
plt.ylabel("Mean contamination (%)")
plt.tight_layout()
#plt.savefig("plot_contamination_stacked_by_cohort.png",dpi=600)
plt.close()

print("Done.")
print("Generated:")
print(" - table1_contamination_per_sample_wide.tsv")
print(" - table2_group_mean_sd.tsv")
print(" - table3_anova.tsv")
print(" - plot_total_contamination_by_cohort.png")
print(" - plot_contamination_stacked_by_cohort.png")
