# -*- coding: utf-8 -*-
"""MAGS_VF_ARG_cleanup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oob3z0tiGzIs6DjIkDdkqK5l2bJciuIG
"""

import pandas as pd
import re

# Load TSV file
df = pd.read_csv("/content/gtdb_arch_with_species.tsv", sep="\t")

def relabel_species(tax):
    if pd.isna(tax):
        return "Unknown"

    # Find genus
    genus_match = re.search(r"g__([^;]+)", tax)
    species_match = re.search(r"s__([^;]*)$", tax)

    # Handle missing genus
    if not genus_match:
        return "Unknown"

    genus = genus_match.group(1).strip()

    # If species is missing or blank → Genus spp.
    if not species_match:
        return f"{genus} spp."

    species = species_match.group(1).strip()

    if species == "":
        return f"{genus} spp."
    else:
        return species

# Apply the relabeling function
df["Relabeled_Species"] = df["Species"].apply(relabel_species)

# Save output
df.to_csv("gtdb_arch_with_species_relabelled.tsv", sep="\t", index=False)

print("Finished! Saved as gtdb_arch_with_species_relabelled.tsv")

import pandas as pd
import re

# --------------------------------------------------
# 1. Load your TSV file
# --------------------------------------------------
df = pd.read_csv("arg_with_species.tsv", sep="\t")

# --------------------------------------------------
# 2. Function: Relabel species
# --------------------------------------------------
def relabel_species(tax):
    if pd.isna(tax):
        return "Unknown"

    genus_match = re.search(r"g__([^;]+)", tax)
    species_match = re.search(r"s__([^;]*)$", tax)

    if not genus_match:
        return "Unknown"

    genus = genus_match.group(1).strip()
    species = species_match.group(1).strip() if species_match else ""

    if species == "":
        return f"{genus} spp."
    else:
        return species

# --------------------------------------------------
# 3. Function: Extract gene name
# --------------------------------------------------
def extract_gene(gene_string):
    if pd.isna(gene_string):
        return "Unknown"

    # Look for gene=something
    match = re.search(r"gene=([^|]+)", gene_string)
    if match:
        return match.group(1).strip()
    return "Unknown"

# --------------------------------------------------
# 4. Apply functions
# --------------------------------------------------
df["Relabeled_Species"] = df["Species"].apply(relabel_species)
df["Gene_clean"] = df["Gene"].apply(extract_gene)

# --------------------------------------------------
# 5. Save processed file
# --------------------------------------------------
output = "arg_with_species_cleaned.tsv"
df.to_csv(output, sep="\t", index=False)

print("DONE! File saved as:", output)

import pandas as pd
import re

# ==========================================
# 1. LOAD FILE
# ==========================================
df = pd.read_csv("vfdb_with_species.tsv", sep="\t")


# ==========================================
# 2. SPECIES CLEANER
# ==========================================
def clean_species(taxon):
    if pd.isna(taxon):
        return "Unclassified spp."

    # extract genus
    g = re.search(r"g__([^;]+)", taxon)
    genus = g.group(1).strip() if g else "Unclassified"

    # extract species
    s = re.search(r"s__([^;]*)$", taxon)
    species = s.group(1).strip() if s else ""

    # if species missing -> genus spp.
    if species == "":
        return f"{genus} spp."
    else:
        return species


# ==========================================
# 3. GENE CLEANER
# ==========================================
def extract_gene(gene_str):
    if pd.isna(gene_str):
        return "Unknown"
    m = re.search(r"gene=([^|]+)", gene_str)
    return m.group(1).strip() if m else "Unknown"


# ==========================================
# 4. CATEGORY CLEANER
# ==========================================
def extract_category(gene_str):
    if pd.isna(gene_str):
        return "Unknown"

    m = re.search(r"category=([^|]+)", gene_str)
    if not m:
        return "Unknown"

    cat = m.group(1)

    # remove VFC codes: __VFC0272_ or _VFC0272_
    cat = re.sub(r"__?VFC\d+_?", "", cat)

    # underscores → spaces
    cat = cat.replace("_", " ")

    return cat.strip()


# ==========================================
# 5. APPLY CLEANERS
# ==========================================
df["Gene_clean"] = df["Gene"].apply(extract_gene)
df["Category_clean"] = df["Gene"].apply(extract_category)
df["Species_clean"] = df["Species"].apply(clean_species)


# ==========================================
# 6. SAVE CLEAN OUTPUT
# ==========================================
out = "vfdb_with_species_cleaned.tsv"
df.to_csv(out, sep="\t", index=False)

print("DONE! Saved:", out)
print(df.head(10).to_string(index=False))
