# -*- coding: utf-8 -*-
"""Metadata_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13WZZk0IQWciUiII7xeg3fY0DZRsUMXbB
"""

import pandas as pd

# Load metadata
df = pd.read_csv("metadata_MAGS_Raw.csv")

# Keep only relevant columns
cols = ["Age", "Sex", "Group"]
df = df[cols]

# ---------------------------
# 1. Age statistics
# ---------------------------

age_df = df.dropna(subset=["Age"])

age_min = age_df["Age"].min()
age_max = age_df["Age"].max()
age_mean = age_df["Age"].mean()
age_sd = age_df["Age"].std()

print("Age range:", age_min, "-", age_max)
print(f"Mean age ± SD: {age_mean:.1f} ± {age_sd:.1f}")

# ---------------------------
# 2. Sex distribution
# ---------------------------

sex_counts = df["Sex"].value_counts()

n_male = sex_counts.get("Male", 0)
n_female = sex_counts.get("Female", 0)

print("Sex counts:")
print(sex_counts)
print(f"Male : Female ratio = {n_male}:{n_female}")

# ---------------------------
# 3. Sample counts per group
# ---------------------------

group_counts = df["Group"].value_counts()

print("Samples per clinical group:")
print(group_counts)

# ---------------------------
# 4. Group-wise age summary (optional, very useful)
# ---------------------------

group_age_summary = (
    df.dropna(subset=["Age"])
      .groupby("Group")["Age"]
      .agg(["count", "min", "max", "mean", "std"])
      .round(1)
)

print("\nGroup-wise age summary:")
print(group_age_summary)