# -*- coding: utf-8 -*-
"""PLS-High_risk_pathobiont.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BPQ7b0HPjUWacoXNTHn65tNxUhmuj0tD
"""

import pandas as pd
import re

# --------------------------------------------------
# Helper function: canonicalize species names
# --------------------------------------------------
def canonical_species(name):
    if pd.isna(name):
        return None
    name = name.lower()
    name = re.sub(r"[._]", " ", name)   # dots/underscores → spaces
    name = re.sub(r"\s+", " ", name)    # collapse whitespace
    return name.strip()

# --------------------------------------------------
# 1. Load input files
# --------------------------------------------------
maaslin = pd.read_csv(
    "/content/Maaslin3_Significant_With_PLS_Component.csv"
)

risk = pd.read_csv(
    "/content/High_Risk_Pathobionts.csv"
)

# --------------------------------------------------
# 2. Canonicalize species names in BOTH tables
# --------------------------------------------------
# MaAsLin2 already has Species_canon, but we normalize again for safety
maaslin["Species_match"] = maaslin["Species_canon"].apply(canonical_species)

# High-risk table: assume column name is 'Species'
# (change if your column name differs)
risk["Species_match"] = risk["Species"].apply(canonical_species)

# --------------------------------------------------
# 3. Select only the risk-related columns to append
# --------------------------------------------------
risk_subset = risk[
    [
        "Species_match",
        "ARG_total",
        "VF_total",
        "ARG_VF_ratio",
        "ARG_VF_Correlation",
        "risk_score",
    ]
]

# --------------------------------------------------
# 4. Merge (LEFT JOIN: keep all MaAsLin2 hits)
# --------------------------------------------------
merged = maaslin.merge(
    risk_subset,
    on="Species_match",
    how="left"
)

# --------------------------------------------------
# 5. Optional: flag which species are high-risk pathobionts
# --------------------------------------------------
merged["High_Risk_Pathobiont"] = merged["risk_score"].notna()

# --------------------------------------------------
# 6. Save output
# --------------------------------------------------
out_file = "Maaslin3_with_ARG_VF_Risk_Metrics.csv"
merged.to_csv(out_file, index=False)

print(f"Merge complete")
print(f"Output saved to: {out_file}")

# --------------------------------------------------
# 7. Quick sanity check
# --------------------------------------------------
print("\nMatched high-risk species:")
print(
    merged.loc[merged["High_Risk_Pathobiont"],
               ["Species_canon", "Component", "risk_score"]]
    .drop_duplicates()
    .sort_values("risk_score", ascending=False)
)

import pandas as pd
import re

# ----------------------------
# 1. Load files
# ----------------------------
maaslin = pd.read_csv("/content/Maaslin3_Significant_With_PLS_Component.csv")
risk = pd.read_csv("/content/High_Risk_Pathobionts.csv")

# ----------------------------
# 2. Canonical species name function
# ----------------------------
def canonical_species(name):
    if pd.isna(name):
        return None

    name = name.lower()

    # replace separators
    name = name.replace(".", " ").replace("_", " ")

    # remove strain / sp identifiers (e.g. sp900542495, sp003451515)
    name = re.sub(r"\bsp\d+\b", "", name)

    # remove single-letter suffixes (A, B, I, etc.)
    name = re.sub(r"\b[a-z]\b", "", name)

    # collapse whitespace
    name = re.sub(r"\s+", " ", name).strip()

    return name

# ----------------------------
# 3. Create canonical columns
# ----------------------------
maaslin["Species_canon_join"] = maaslin["Species_raw"].apply(canonical_species)
risk["Species_canon_join"] = risk["Species"].apply(canonical_species)

# ----------------------------
# 4. Deduplicate risk table (important)
# ----------------------------
risk_unique = (
    risk
    .drop_duplicates(subset="Species_canon_join")
    .loc[:, [
        "Species_canon_join",
        "ARG_total",
        "VF_total",
        "ARG_VF_ratio",
        "ARG_VF_Correlation",
        "risk_score"
    ]]
)

# ----------------------------
# 5. Merge (MaAsLin2 → High-risk)
# ----------------------------
merged = maaslin.merge(
    risk_unique,
    on="Species_canon_join",
    how="left"
)

# ----------------------------
# 6. Optional: flag matched species
# ----------------------------
merged["High_Risk_Match"] = merged["risk_score"].notna()

# ----------------------------
# 7. Save output
# ----------------------------
merged.to_csv(
    "MaAsLin3_With_HighRisk_Pathobiont_Annotations.csv",
    index=False
)

print("Merge complete")
print("Total MaAsLin2 species:", maaslin.shape[0])
print("Matched high-risk species:", merged["High_Risk_Match"].sum())
